# **MATRICS**

# VECTOR
- IT is numpy array
- example
**A=np.array([1,2,3,4,5])**

# Vector Addition
Two vectors of equal length can be added together to create a new third vector.
c = a + b

The new vector has the same length as the other two vectors. Each element of the new
vector is calculated as the addition of the elements of the other vectors at the same index; for
example:
c = (a1 + b1, a2 + b2, a3 + b3)

In [1]:
import numpy as np
A=np.array([1,2,3,4,5,6,7,8,9])
B=np.array([9,8,7,6,5,4,3,2,1])
C=A+B
print(C)

[10 10 10 10 10 10 10 10 10]


 # Vector Subtraction
One vector can be subtracted from another vector of equal length to create a new third vector.
- c = a − b


 - As with addition, the new vector has the same length as the parent vectors and each element
of the new vector is calculated as the subtraction of the elements at the same indices.
c = (a1 − b1, a2 − b2, a3 − b3)

In [2]:
import numpy as np
A=np.array([2,4,5,6,7,8])
B=np.array([3,3,5,6,4,3])
C=A-B
print(C)

[-1  1  0  0  3  5]


 # Vector Multiplication
Two vectors of equal length can be multiplied together.
- c = a × b

As with addition and subtraction, this operation is performed element-wise to result in a
new vector of the same length.
- c = (a1 × b1, a2 × b2, a3 × b3)

or
 - c = (a1b1, a2b2, a3b3)

In [1]:
import numpy as np
A=np.array([2,3,4,5,6])
B=np.array([5,6,4,4,2])
C=A*B
print(C)

[10 18 16 20 12]


 # Vector Division
Two vectors of equal length can be divided.
- c = a/b

As with other arithmetic operations, this operation is performed element-wise to result in a
new vector of the same length.
 - c = (a1
b1
, a2
b2
, a3
b3
)

In [2]:
import numpy as np
A=np.array([2,3,4,5,6,7])
B=np.array([3,5,6,7,7,6])
C=A/B
print(C)

[0.66666667 0.6        0.66666667 0.71428571 0.85714286 1.16666667]


 # Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. This is called the dot product, named because of the dot operator used when describing
the operation.
The dot product is the key tool for calculating vector projections, vector decomposi-
tions, and determining orthogonality. The name dot product comes from the symbol
used to denote it.

- c = a · b

The operation can be used in machine learning to calculate the weighted sum of a vector.
The dot product is calculated as follows:
- c = (a1 × b1 + a2 × b2 + a3 × b3)

or
 - c = (a1b1 + a2b2 + a3b3)

We can calculate the dot product between two vectors in Python using the dot() function
on a NumPy array.

In [3]:
import numpy as np
A=np.array([2,3,4,5,6,5])
B=np.array([4,5,5,5,6,7])
c=np.dot(A,B)
print(c)

139


 # Vector-Scalar Multiplication
A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. To keep
notation simple, we will use lowercase s to represent the scalar value.
- c = s × v

or
- c = sv

The multiplication is performed on each element of the vector to result in a new scaled
vector of the same length.
- c = (s × v1, s × v2, s × v3)

In [5]:
import numpy as np
A=np.arange(12)
print(A)
B=0.2
C=A*B
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2]


# **Vector Norm**
Calculating the size or length of a vector is often required either directly or as part of a broader
vector or vector-matrix operation. The length of the vector is referred to as the vector norm or
the vector’s magnitude

# L1 NORM

In [4]:
import numpy as np
A=np.arange(12)
print(A)
Norm=np.linalg.norm(A,1)
print(Norm)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
66.0


In [9]:
import numpy as np
A= np.array([1,3,4,6,7,6,45,4,3,2])
print(A)
Norm=np.linalg.norm(A,1)
print(Norm)

[ 1  3  4  6  7  6 45  4  3  2]
81.0


# L2 NORM

In [1]:
import numpy as np
A=np.array([1,2,3,4,5,6,7,8,9])
l2=np.linalg.norm(A)
print(l2)

16.881943016134134


# L3  NORM

In [3]:
import numpy as np
A=np.array([1,2,3,54,65,4,4,5,6,6,5,76])
maxnorm=np.linalg.norm(A,np.inf)
print(maxnorm)

76.0


# Matrices and Matrix Arithmetic
- THE DIMMINSION MUST BE SAME

- # Matrix Addition

In [6]:
import numpy as np
A=np.array([[1,2,3,4,5],[6,7,8,9,6]])
print(A)
print("\n")
B=np.array([[4,6,7,8,6],[6,8,4,3,6]])
print(B)
C=A+B
print("\n")
print(C)

[[1 2 3 4 5]
 [6 7 8 9 6]]


[[4 6 7 8 6]
 [6 8 4 3 6]]


[[ 5  8 10 12 11]
 [12 15 12 12 12]]


- # Matrix Subtraction

In [10]:
import numpy as np
A=np.array([[5,7,6,4,7],[3,5,6,6,4]])
print(A)
print("\n")
B=np.array([[2,4,5,6,7],[5,8,5,4,3]])
print(B)
print("\n")
C=A-B
print(C)

[[5 7 6 4 7]
 [3 5 6 6 4]]


[[2 4 5 6 7]
 [5 8 5 4 3]]


[[ 3  3  1 -2  0]
 [-2 -3  1  2  1]]


- # Matrix Multiplication (Hadamard Product)

In [3]:
import numpy as np
A=np.array([[2,3,4,5,6],[7,8,9,10,11]])
print(A)
print("\n")
B=np.array([[3,5,6,7,7],[6,5,4,3,2]])
print(B)
C= A*B
print("\n") 
print(C)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


[[3 5 6 7 7]
 [6 5 4 3 2]]


[[ 6 15 24 35 42]
 [42 40 36 30 22]]


- # Matrix Division

In [4]:
import numpy as np
A=np.array([[3,4,5,6,7],[5,7,8,5,4]])
print(A)
print("\n")
B=np.array([[2,3,4,5,6],[7,8,9,10,11]])
print(B)
C=A/B
print("\n")

print(C)

[[3 4 5 6 7]
 [5 7 8 5 4]]


[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


[[1.5        1.33333333 1.25       1.2        1.16666667]
 [0.71428571 0.875      0.88888889 0.5        0.36363636]]


- # Matrix-Matrix Multiplication
- dot multiflication

In [10]:
import numpy as np
A=np.array([[2,4,7,5,4,3],[5,6,4,7,3,4]])
print(A)
print("\n")
B=np.array([[4,6,4,3,5,6],[5,7,5,3,4,5]])
print(B)
bt=B.T
print(bt)
C=A.dot(bt)
print("\n")
print(C)

[[2 4 7 5 4 3]
 [5 6 4 7 3 4]]


[[4 6 4 3 5 6]
 [5 7 5 3 4 5]]
[[4 5]
 [6 7]
 [4 5]
 [3 3]
 [5 4]
 [6 5]]


[[113 119]
 [132 140]]


 - # Matrix-Vector Multiplication

In [ ]:
import numpy as  np
A=np.array([[2,3,4,5,6],
            [7,8,9,10,11]])
print(A)
b=np.array([1,2,3,4,5])
C=A.dot(b)
print("\n")
print(C)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


[ 70 145]


- # Matrix-Scalar Multiplication

In [2]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
B=3
C=A*B
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


# Types of Matrices

-  # Square Matrix
- the nuber of row equal to number of column
- n=m

In [4]:
import numpy as np

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("---------SXUARE MATRIX---------")
print(A)

---------SXUARE MATRIX---------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- # Symmetric Matrix
- A=A^t

In [6]:
import numpy as np
A=np.array([[1,2,3,4,5],
           [2,1,2,3,4],
           [3,2,1,2,3],
           [4,3,2,1,2],
           [5,4,3,2,1]])
print("---------SYMMETRIC MATRIX---------")
print(A)
At=A.T
print("\n") 
print("Transpose of the matrix:")
print(At)

---------SYMMETRIC MATRIX---------
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Transpose of the matrix:
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


- # Triangular Matrix

In [4]:
import numpy as np
A=np.array([[1,2,3,4,5],
            [4,6,7,8,9],
            [2,3,4,5,6],
            [3,4,5,6,7],
            [1,2,3,4,5]])
print("---------DIAGONAL MATRIX---------")
print(A)
upper_triangle = np.triu(A)
print("\n")
print("Upper triangular part of the matrix:")
print(upper_triangle)
lower_triangle = np.tril(A)
print("\n") 
print("Lower triangular part of the matrix:")
print(lower_triangle)

---------DIAGONAL MATRIX---------
[[1 2 3 4 5]
 [4 6 7 8 9]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [1 2 3 4 5]]


Upper triangular part of the matrix:
[[1 2 3 4 5]
 [0 6 7 8 9]
 [0 0 4 5 6]
 [0 0 0 6 7]
 [0 0 0 0 5]]


Lower triangular part of the matrix:
[[1 0 0 0 0]
 [4 6 0 0 0]
 [2 3 4 0 0]
 [3 4 5 6 0]
 [1 2 3 4 5]]


# Matrix Operations

1. Transpose
2. Inverse
3. Trace
4. Determinant
5. Rank


# 1. Transpose

In [3]:
import numpy as np
A=np.array([[1,2,3,4,5],
            [5,6,7,8,9],
            [9,8,7,6,5],
            [4,3,2,1,0],
            [0,1,2,3,4]])
print(A)
print("\n")
tanspose=A.T
print(tanspose)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [9 8 7 6 5]
 [4 3 2 1 0]
 [0 1 2 3 4]]


[[1 5 9 4 0]
 [2 6 8 3 1]
 [3 7 7 2 2]
 [4 8 6 1 3]
 [5 9 5 0 4]]


# 2. Inverse


In [11]:
import numpy as np
A=np.array([[1,2,3],[4,7,6],[7,8,9]])
print(A)
print("\n")
det=np.linalg.det(A)
print(det)
print("\n")
b=np.linalg.inv(A)
print(b)



[[1 2 3]
 [4 7 6]
 [7 8 9]]


-24.000000000000004


[[-0.625      -0.25        0.375     ]
 [-0.25        0.5        -0.25      ]
 [ 0.70833333 -0.25        0.04166667]]


# 3. Trace

In [13]:
import numpy as np
A=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(A)
print("\n")
trace=np.linalg.trace(A)
print(trace)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


9


# 4. Determinant

In [17]:
import numpy as np
A=np.array([[1,2,3,4,5],
            [5,6,7,8,9],
            [9,8,7,6,5],
            [4,3,2,1,0],
            [0,1,9,3,4]])
print(A)
print("\n")
det=np.linalg.det(A)
print(det)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [9 8 7 6 5]
 [4 3 2 1 0]
 [0 1 9 3 4]]


3.865418435582966e-29


 # 5. Rank


In [2]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
rank=np.linalg.matrix_rank(A)
print("\n") 
print(rank)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2


# Sparse Matrices
1. Sparse Matrix
2. Problems with Sparsity
3. Sparse Matrices in Machine Learning
4. Working with Sparse Matrices
5. Sparse Matrices in Python

In [5]:
import numpy as np
import scipy.sparse as sp


A = np.array([[2, 0, 0, 0, 0],
              [0, 0, 0, 7, 0],
              [0, 0, 0, 0, 0],
              [0, 0, 8, 0, 0],
              [0, 0, 0, 0, 9]])
print(A)

sparse_matrix = sp.csr_matrix(A)
print("\n")
print(sparse_matrix)

print(f"size: {A.shape}")

sparsity = 1.0 - np.count_nonzero(A) / A.size
print(f"sparsity: {sparsity}")

[[2 0 0 0 0]
 [0 0 0 7 0]
 [0 0 0 0 0]
 [0 0 8 0 0]
 [0 0 0 0 9]]


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (5, 5)>
  Coords	Values
  (0, 0)	2
  (1, 3)	7
  (3, 2)	8
  (4, 4)	9
size: (5, 5)
sparsity: 0.84


In [ ]:
import numpy as np
from scipy.sparse import csr_matrix


dense_Matrix = np.array([
  [0, 0, 3, 0, 4],
  [0, 0, 5, 7, 0],
  [0, 0, 0, 0, 0],
  [0, 2, 6, 0, 0]
])


sparse_matrix = csr_matrix(dense_Matrix)

print("The full dense matrix looks like this:")
print(dense_Matrix)
print("\nBut the sparse matrix only stores the 'oases':")
print(sparse_matrix)

print("\nIts CSR arrays are:")
print(" data (values):", sparse_matrix.data)
print(" col indices:  ", sparse_matrix.indices)
print(" row pointers: ", sparse_matrix.indptr)


vector = np.array([1, 2, 3, 4, 5])
result = sparse_matrix.dot(vector) 
print("\nResult of multiplying the sparse matrix by a vector:", result)


The full dense matrix looks like this:
[[0 0 3 0 4]
 [0 0 5 7 0]
 [0 0 0 0 0]
 [0 2 6 0 0]]

But the sparse matrix only stores the 'oases':
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (4, 5)>
  Coords	Values
  (0, 2)	3
  (0, 4)	4
  (1, 2)	5
  (1, 3)	7
  (3, 1)	2
  (3, 2)	6

Its CSR arrays are:
 data (values): [3 4 5 7 2 6]
 col indices:   [2 4 2 3 1 2]
 row pointers:  [0 2 4 4 6]

Result of multiplying the sparse matrix by a vector: [29 43  0 22]


# Tensors and Tensor Arithmetic
1. What are Tensors
2. Tensors in Python
3. Tensor Arithmetic
4. Tensor Product

# What are Tensors
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional
array

In [8]:
import numpy as np
A=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


#  ADDITION OF TENSOR

In [12]:
import numpy as np
print(" 3D array (tensor) 1")
A=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(A)
print(" 3D array (tensor) 2")
B=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(B)
print(" Addition of two tensors")
c=A+B
print(c)

 3D array (tensor) 1
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 3D array (tensor) 2
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 Addition of two tensors
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


# SUBTRACTION

In [13]:
import numpy as np
print(" 3D array (tensor) 1")
A=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(A)
print(" 3D array (tensor) 2")
B=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(B)
print(" SUBTRACTION of two tensors")
c=A-B
print(c)

 3D array (tensor) 1
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 3D array (tensor) 2
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 SUBTRACTION of two tensors
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


 # MULTIFLICATION

In [14]:
import numpy as np
print(" 3D array (tensor) 1")
A=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(A)
print(" 3D array (tensor) 2")
B=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(B)
print(" MULTIFLICATION of two tensors")
c=A*B
print(c)

 3D array (tensor) 1
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 3D array (tensor) 2
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 MULTIFLICATION of two tensors
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [16]:
import numpy as np
print(" 3D array (tensor) 1")
A=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(A)
print(" 3D array (tensor) 2")
B=np.array([
[[1,2,3],
[4,5,6],
[7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(B)
print(" dot multiflication of two tensors")
c=np.tensordot(A,B)
print(c)

 3D array (tensor) 1
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 3D array (tensor) 2
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
 dot multiflication of two tensors
[[ 828  873  918]
 [2088 2223 2358]
 [3348 3573 3798]]


#  Write your own functions to implement each tensor arithmetic operation

In [17]:
def tensor_add(tensor1, tensor2):
    if len(tensor1) != len(tensor2) or len(tensor1[0]) != len(tensor2[0]) or len(tensor1[0][0]) != len(tensor2[0][0]):
        raise ValueError("Tensors must have the same shape for addition.")
    
    depth = len(tensor1)
    rows = len(tensor1[0])
    cols = len(tensor1[0][0])
    
    result = [[[0 for _ in range(cols)] for _ in range(rows)] for _ in range(depth)]
    
    for i in range(depth):
        for j in range(rows):
            for k in range(cols):
                result[i][j][k] = tensor1[i][j][k] + tensor2[i][j][k]
    return result
def tensor_subtract(tensor1, tensor2):
    if len(tensor1) != len(tensor2) or len(tensor1[0]) != len(tensor2[0]) or len(tensor1[0][0]) != len(tensor2[0][0]):
        raise ValueError("Tensors must have the same shape for subtraction.")
    
    depth = len(tensor1)
    rows = len(tensor1[0])
    cols = len(tensor1[0][0])
    
    result = [[[0 for _ in range(cols)] for _ in range(rows)] for _ in range(depth)]
    
    for i in range(depth):
        for j in range(rows):
            for k in range(cols):
                result[i][j][k] = tensor1[i][j][k] - tensor2[i][j][k]
    return result
def tensor_elementwise_multiply(tensor1, tensor2):
    if len(tensor1) != len(tensor2) or len(tensor1[0]) != len(tensor2[0]) or len(tensor1[0][0]) != len(tensor2[0][0]):
        raise ValueError("Tensors must have the same shape for multiplication.")
    
    depth = len(tensor1)
    rows = len(tensor1[0])
    cols = len(tensor1[0][0])
    
    result = [[[0 for _ in range(cols)] for _ in range(rows)] for _ in range(depth)]
    
    for i in range(depth):
        for j in range(rows):
            for k in range(cols):
                result[i][j][k] = tensor1[i][j][k] * tensor2[i][j][k]
    return result
# The tensor you provided
tensor_a = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
    [[21, 22, 23], [24, 25, 26], [27, 28, 29]]
]

# A second tensor for operations
tensor_b = [
    [[2, 2, 2], [2, 2, 2], [2, 2, 2]],
    [[2, 2, 2], [2, 2, 2], [2, 2, 2]],
    [[2, 2, 2], [2, 2, 2], [2, 2, 2]]
]

# Perform and print the results
print("Tensor A + Tensor B:")
print(tensor_add(tensor_a, tensor_b))

print("\nTensor A - Tensor B:")
print(tensor_subtract(tensor_a, tensor_b))

print("\nTensor A * Tensor B (element-wise):")
print(tensor_elementwise_multiply(tensor_a, tensor_b))

Tensor A + Tensor B:
[[[3, 4, 5], [6, 7, 8], [9, 10, 11]], [[13, 14, 15], [16, 17, 18], [19, 20, 21]], [[23, 24, 25], [26, 27, 28], [29, 30, 31]]]

Tensor A - Tensor B:
[[[-1, 0, 1], [2, 3, 4], [5, 6, 7]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

Tensor A * Tensor B (element-wise):
[[[2, 4, 6], [8, 10, 12], [14, 16, 18]], [[22, 24, 26], [28, 30, 32], [34, 36, 38]], [[42, 44, 46], [48, 50, 52], [54, 56, 58]]]
