# **MATRICS**

# VECTOR
- IT is numpy array
- example
**A=np.array([1,2,3,4,5])**

# Vector Addition
Two vectors of equal length can be added together to create a new third vector.
c = a + b

The new vector has the same length as the other two vectors. Each element of the new
vector is calculated as the addition of the elements of the other vectors at the same index; for
example:
c = (a1 + b1, a2 + b2, a3 + b3)

In [1]:
import numpy as np
A=np.array([1,2,3,4,5,6,7,8,9])
B=np.array([9,8,7,6,5,4,3,2,1])
C=A+B
print(C)

[10 10 10 10 10 10 10 10 10]


 # Vector Subtraction
One vector can be subtracted from another vector of equal length to create a new third vector.
- c = a − b


 - As with addition, the new vector has the same length as the parent vectors and each element
of the new vector is calculated as the subtraction of the elements at the same indices.
c = (a1 − b1, a2 − b2, a3 − b3)

In [2]:
import numpy as np
A=np.array([2,4,5,6,7,8])
B=np.array([3,3,5,6,4,3])
C=A-B
print(C)

[-1  1  0  0  3  5]


 # Vector Multiplication
Two vectors of equal length can be multiplied together.
- c = a × b

As with addition and subtraction, this operation is performed element-wise to result in a
new vector of the same length.
- c = (a1 × b1, a2 × b2, a3 × b3)

or
 - c = (a1b1, a2b2, a3b3)

In [1]:
import numpy as np
A=np.array([2,3,4,5,6])
B=np.array([5,6,4,4,2])
C=A*B
print(C)

[10 18 16 20 12]


 # Vector Division
Two vectors of equal length can be divided.
- c = a/b

As with other arithmetic operations, this operation is performed element-wise to result in a
new vector of the same length.
 - c = (a1
b1
, a2
b2
, a3
b3
)

In [2]:
import numpy as np
A=np.array([2,3,4,5,6,7])
B=np.array([3,5,6,7,7,6])
C=A/B
print(C)

[0.66666667 0.6        0.66666667 0.71428571 0.85714286 1.16666667]


 # Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. This is called the dot product, named because of the dot operator used when describing
the operation.
The dot product is the key tool for calculating vector projections, vector decomposi-
tions, and determining orthogonality. The name dot product comes from the symbol
used to denote it.

- c = a · b

The operation can be used in machine learning to calculate the weighted sum of a vector.
The dot product is calculated as follows:
- c = (a1 × b1 + a2 × b2 + a3 × b3)

or
 - c = (a1b1 + a2b2 + a3b3)

We can calculate the dot product between two vectors in Python using the dot() function
on a NumPy array.

In [3]:
import numpy as np
A=np.array([2,3,4,5,6,5])
B=np.array([4,5,5,5,6,7])
c=np.dot(A,B)
print(c)

139


 # Vector-Scalar Multiplication
A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. To keep
notation simple, we will use lowercase s to represent the scalar value.
- c = s × v

or
- c = sv

The multiplication is performed on each element of the vector to result in a new scaled
vector of the same length.
- c = (s × v1, s × v2, s × v3)

In [5]:
import numpy as np
A=np.arange(12)
print(A)
B=0.2
C=A*B
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2]


# **Vector Norm**
Calculating the size or length of a vector is often required either directly or as part of a broader
vector or vector-matrix operation. The length of the vector is referred to as the vector norm or
the vector’s magnitude

# L1 NORM

In [4]:
import numpy as np
A=np.arange(12)
print(A)
Norm=np.linalg.norm(A,1)
print(Norm)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
66.0


In [9]:
import numpy as np
A= np.array([1,3,4,6,7,6,45,4,3,2])
print(A)
Norm=np.linalg.norm(A,1)
print(Norm)

[ 1  3  4  6  7  6 45  4  3  2]
81.0


# L2 NORM

In [1]:
import numpy as np
A=np.array([1,2,3,4,5,6,7,8,9])
l2=np.linalg.norm(A)
print(l2)

16.881943016134134


# L3  NORM

In [3]:
import numpy as np
A=np.array([1,2,3,54,65,4,4,5,6,6,5,76])
maxnorm=np.linalg.norm(A,np.inf)
print(maxnorm)

76.0


# Matrices and Matrix Arithmetic
- THE DIMMINSION MUST BE SAME

- # Matrix Addition

In [6]:
import numpy as np
A=np.array([[1,2,3,4,5],[6,7,8,9,6]])
print(A)
print("\n")
B=np.array([[4,6,7,8,6],[6,8,4,3,6]])
print(B)
C=A+B
print("\n")
print(C)

[[1 2 3 4 5]
 [6 7 8 9 6]]


[[4 6 7 8 6]
 [6 8 4 3 6]]


[[ 5  8 10 12 11]
 [12 15 12 12 12]]


- # Matrix Subtraction

In [10]:
import numpy as np
A=np.array([[5,7,6,4,7],[3,5,6,6,4]])
print(A)
print("\n")
B=np.array([[2,4,5,6,7],[5,8,5,4,3]])
print(B)
print("\n")
C=A-B
print(C)

[[5 7 6 4 7]
 [3 5 6 6 4]]


[[2 4 5 6 7]
 [5 8 5 4 3]]


[[ 3  3  1 -2  0]
 [-2 -3  1  2  1]]
